# Numpy <hr style="border:2.5px solid #fce100"></hr>


<b> Norbert Francis C. Baylon </b>
<br>Computer Engineering Student
<br> Technological University of the Philippines Visayas

In [1]:
import numpy as np
from scipy import stats
from statistics import multimode

# 1-D Array

In [2]:
my_array = np.array([1,2,3])

In [3]:
np.shape(my_array)

(3,)

# 2-D Array

In [4]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.shape(my_array)

(2, 3)

In [6]:
trans_array = my_array.T

In [7]:
np.shape(trans_array)

(3, 2)

In [8]:
trans_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
np.sum(trans_array,axis=0)

array([ 6, 15])

In [10]:
np.sum(trans_array,axis=1)

array([5, 7, 9])

# Measure of Central Tendency

In [11]:
resistance = np.array([
    [3,9.1,9.3,9.5,9.8,9.8,10.4,10.4,10.5,10.5,11], #Dataset 1/Jaguar
    [9.1,9.1,9.1,9.2,9.2,9.9,10.1,10.8,11,20, np.nan] #Dataset 2/Panther
])

In [12]:
resistance

array([[ 3. ,  9.1,  9.3,  9.5,  9.8,  9.8, 10.4, 10.4, 10.5, 10.5, 11. ],
       [ 9.1,  9.1,  9.1,  9.2,  9.2,  9.9, 10.1, 10.8, 11. , 20. ,  nan]])

In [13]:
np.shape(resistance)

(2, 11)

In [14]:
np.mean(resistance, axis = 0)

array([ 6.05,  9.1 ,  9.2 ,  9.35,  9.5 ,  9.85, 10.25, 10.6 , 10.75,
       15.25,   nan])

In [15]:
np.mean(resistance, axis = 1)

array([9.39090909,        nan])

In [16]:
np.nanmean(resistance, axis = 1)

array([ 9.39090909, 10.75      ])

In [17]:
jag_mean = np.nanmean(resistance, axis = 1)[0]
pan_mean = np.nanmean(resistance, axis = 1)[1]

print(f'Jaguar_mean = {jag_mean:.2f} ohms')
print(f'Panther_mean = {pan_mean:.2f} ohms')

Jaguar_mean = 9.39 ohms
Panther_mean = 10.75 ohms


In [18]:
np.median(resistance, axis = 1)

array([9.8, nan])

In [19]:
np.nanmedian(resistance, axis = 1)

array([9.8 , 9.55])

In [20]:
jag_median = np.nanmedian(resistance, axis = 1)[0]
pan_median = np.nanmedian(resistance, axis = 1)[1]

print(f'Jaguar_mean = {jag_median:.2f} ohms')
print(f'Panther_mean = {pan_median:.2f} ohms')

Jaguar_mean = 9.80 ohms
Panther_mean = 9.55 ohms


In [21]:
stats.mode(resistance, axis = 1)

ModeResult(mode=array([9.8, 9.1]), count=array([2, 3]))

In [22]:
my_array = [1,1,2,2,3,4,5]
multimode(my_array)

[1, 2]

In [23]:
jag_res = resistance[0]

print("Jaguar mode: ")
for i in multimode(jag_res):
    print(f'{i} ohms')

Jaguar mode: 
9.8 ohms
10.4 ohms
10.5 ohms


In [24]:
pan_res = resistance[1]

print("Panther mode: ")
for i in multimode(pan_res):
    print(f'{i} ohms')

Panther mode: 
9.1 ohms


# Measures of Variability

In [25]:
resistance = np.array([
    [3,9.1,9.3,9.5,9.8,9.8,10.4,10.4,10.5,10.5,11], #Dataset 1/Jaguar
    [9.1,9.1,9.1,9.2,9.2,9.9,10.1,10.8,11,20, np.nan] #Dataset 2/Panther
])
resistance

array([[ 3. ,  9.1,  9.3,  9.5,  9.8,  9.8, 10.4, 10.4, 10.5, 10.5, 11. ],
       [ 9.1,  9.1,  9.1,  9.2,  9.2,  9.9, 10.1, 10.8, 11. , 20. ,  nan]])

In [26]:
res_max = np.nanmax(resistance, axis = 1)
res_min = np.nanmin(resistance, axis = 1)

res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [27]:
print(f'Jaguar_range = {res_range[0]:.2f} ohms')
print(f'Panther_range = {res_range[1]:.2f} ohms')

Jaguar_range = 8.00 ohms
Panther_range = 10.90 ohms


In [28]:
res_Q1 = np.nanpercentile(resistance, 25, axis = 1)
res_Q1

array([9.4  , 9.125])

In [29]:
res_Q2 = np.nanpercentile(resistance, 50, axis = 1)
res_Q2

array([9.8 , 9.55])

In [30]:
res_Q3 = np.nanpercentile(resistance, 75, axis = 1)
res_Q3

array([10.45 , 10.625])

In [31]:
print(f'Jaguar IQR = {res_Q3[0] - res_Q1[0]:.2f} ohms')
print(f'Panther IQR = {res_Q3[1] - res_Q1[1]:.2f} ohms')

Jaguar IQR = 1.05 ohms
Panther IQR = 1.50 ohms


In [32]:
res_var = np.nanvar(resistance, ddof = 1, axis = 1)
res_var

array([ 4.83690909, 11.08277778])

In [33]:
print(f'Jaguar Variance = {res_var[0]:.2f} ohms')
print(f'Panther Variance = {res_var[1]:.2f} ohms')

Jaguar Variance = 4.84 ohms
Panther Variance = 11.08 ohms


In [34]:
res_std = np.nanstd(resistance, ddof = 1, axis = 1)
res_std

array([2.19929741, 3.32908062])

In [35]:
print(f'Jaguar Std Deviation = {res_std[0]:.2f} ohms')
print(f'Panther Std Deviation = {res_std[1]:.2f} ohms')

Jaguar Std Deviation = 2.20 ohms
Panther Std Deviation = 3.33 ohms
