# Numpy <hr style="border:2.5px solid #fce100"></hr>


<b> Norbert Francis C. Baylon </b>
<br>Computer Engineering Student
<br> Technological University of the Philippines Visayas

In [2]:
import numpy as np

# 1-D Array

In [3]:
my_array = np.array([1,2,3])

In [4]:
np.shape(my_array)

(3,)

# 2-D Array

In [5]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.shape(my_array)

(2, 3)

In [7]:
trans_array = my_array.T

In [8]:
np.shape(trans_array)

(3, 2)

In [9]:
trans_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
np.sum(trans_array,axis=0)

array([ 6, 15])

In [11]:
np.sum(trans_array,axis=1)

array([5, 7, 9])

# Measure of Central Tendency

In [ ]:
resistance = np.array([
    [3,9.1,9.3,9.5,9.8,9.8,10.4,10.4,10.5,10.5,11], #Dataset 1/Jaguar
    [9.1,9.1,9.1,9.2,9.2,9.9,9.9,10.1,10.8,11,20] #Dataset 2/Panther
])

In [14]:
resistance

array([[ 3. ,  9.1,  9.3,  9.5,  9.8,  9.8, 10.4, 10.4, 10.5, 10.5, 11. ],
       [ 9.1,  9.1,  9.1,  9.2,  9.2,  9.9,  9.9, 10.1, 10.8, 11. , 20. ]])

In [15]:
np.mean(resistance, axis = 1)

array([ 9.39090909, 10.67272727])

In [16]:
np.median(resistance, axis = 1)

array([9.8, 9.9])